modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory
license="MIT"
[[mods]] #mandatory
modId="tgearbox" #mandatory
version="1.0" #mandatory
displayName="Tinkers' Gearbox" #mandatory
authors="Chemiofitor"
description='''
A lib for the Create and the TiC
'''
[[dependencies.tgearbox]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.tgearbox]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.tgearbox]]
modId="create"
mandatory=true
versionRange="[6.0.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.tgearbox]]
modId="tconstruct"
mandatory=true
versionRange="[3.10.1.0,)"
ordering="NONE"
side="BOTH"